### ISSUE TITLE
Concat vectors

### ISSUE THREAD

**Issue by Chriscbr** [bodil/im-rs#106]
Would it be possible to add an implementation of "concat" as a standard method for immutable vectors? Often I find it's useful for writing more concise code to have functions that return the data structure itself. I know `im::vector::Vector` implements a [append](https://docs.rs/im/10.0.0/im/vector/struct.Vector.html#method.append) method, but it only modifies the calling data structure, making it slightly more awkward in some situations. Would a concat method work against the main ideas / backing implementation of this library, or would it be something that could be added in the future [concat trait](https://doc.rust-lang.org/nightly/std/slice/trait.Concat.html)?

This is the code I've been using as a workaround - AFAIK since the `im` crate does lazy cloning, the operation shouldn't be that expensive:
```rust
fn concat_vectors<T: Clone>(vec1: Vector<T>, vec2: Vector<T>) -> Vector<T> {
    let mut ret_vec = vec1.clone();
    ret_vec.append(vec2);
    ret_vec
}
```

**Comment by bodil** [comment]
`Vector` implements `Add`, so you should be able to just go `vec1 + vec2` to achieve the above. And, in your example, you already own `vec1` so you shouldn't need to clone it at all.
