### ISSUE TITLE
New release for new sized-chunks?

### ISSUE THREAD

**Issue by RalfJung** [bodil/im-rs#109]
https://github.com/bodil/sized-chunks/pull/3 fixes a critical soundness issue in sized-chunks where some non-null pointers were zero-initialized. With https://github.com/rust-lang/rust/pull/66059 we are moving towards better detecting such errors, and making code panic instead of silently causing UB. Unfortunately, cargo depends on im-rc 13.0.0 which still depends on the buggy sized-chunks 0.3.0. So, with that extra error detection we want to do, cargo breaks.

Is there any chance of doing a new release of im-rc that includes https://github.com/bodil/sized-chunks/pull/3?

**Comment by bodil** [comment]
I've been holding off on a release because the increased rustc version requirement suggests a breaking change, but given a compelling reason (such as this), I'd be happy to tag one.

**Comment by bodil** [comment]
14.0.0 tagged and published.

**Comment by RalfJung** [comment]
Thanks a lot!
