### ISSUE TITLE
What is the complexity of Vector::clone?

### ISSUE THREAD

**Issue by SimonSapin** [bodil/im-rs#114]
https://docs.rs/im/14.0.0/im/vector/enum.Vector.html#impl-Clone doesn’t have a doc-comment like inherent methods do.

**Comment by SimonSapin** [comment]
My reading of the code is:

* `Vector::clone` delegates to `InlineArray::clone`, `Ref::clone`, or `RRB`
* `InlineArray::clone` is O(n) but n is bounded by the capacity of `InlineArray` which is a compile-time constant. So it can be thought of as O(1) with a potentially-large constant factor.
* `Ref` is either `Arc` or `Rc`, so `Ref::clone` is a refcount increment which is O(1).
* `RRB`’s fields are all `usize` or `Ref<_>`, its `clone` is similarly O(1).

So I think the answer is O(1). Does that sound right?

**Comment by bodil** [comment]
It's "effectively" O(1) with the caveat you noted, that inline vectors will have their entire contents cloned, which is O(n) but with a bounded n. I'll add a doc block to it.
