### ISSUE TITLE
iter() behaviour for XxxMap

### ISSUE THREAD

**Issue by hh9527** [bodil/im-rs#121]
`HashMap::iter()` should yield `(&K, &V)`, not `&V`.

and

`HashMap::iter_mut()`

So does OrdMap

As same as in `std`.

**Comment by bodil** [comment]
But the `HashMap` iterator currently yields `&(K, V)`, not `&V`?

The mutable iterator only yields `&mut V`, though, I agree it'd be better if it yielded `(&K, &mut V)`.

**Comment by hh9527** [comment]
sorry, my mistake. only iter_mut()
