### ISSUE TITLE
Pool feature unavailable on im_rc

### ISSUE THREAD

**Issue by itamarst** [bodil/im-rs#122]
I can use the pool feature on `im`, but when I try to use it on `im_rc` it fails for some reason.

**Comment by itamarst** [comment]
(Other than that minor issue it's been a pleasure to work with, so thanks for all your efforts).

**Comment by bodil** [comment]
I actually just fixed that earlier today, there should be a new release out fairly soon.

**Comment by itamarst** [comment]
Thank you!
