### ISSUE TITLE
Converting from Vector to Vec and HashSet

### ISSUE THREAD

**Issue by paytonrules** [bodil/im-rs#137]
I apologize in advance for opening an issue here, because while I cannot for the life of me figure this out, even after browsing the code, I suspect this is actually possible and I just can't find it. 

Specifically I'd like to be able to convert a Vector to a HashSet just like I can with a Vec:

```
    fn hashset_conversion() {
        let vector = vector!([1,2,3]);
        let vec = vec!([1, 2, 3]);

        let one_set = HashSet::from(vec);
        let two_set = HashSet::from(vector); // This line fails.
```

Unfortunately this causes the error

```
error[E0277]: the trait bound `im::hash::set::HashSet<_, _>: std::convert::From<im::vector::Vector<[{integer}; 3]>>` is not satisfied
   --> src/deck.rs:214:23
    |
214 |         let two_set = HashSet::from(vector);
    |                       ^^^^^^^^^^^^^ the trait `std::convert::From<im::vector::Vector<[{integer}; 3]>>` is not implemented for `im::hash::set::HashSet<_, _>`
```

I would try converting to `Vec` and then to `HashSet` but for the life of me I can't figure out that either (converting from Vector to Vec) even though I'm 99% sure that has to be possible.

So to sum-up, it looks like there are missing conversions to me, but I'm a novice Rust programmer so it's probably I just can't find them.

**Comment by bodil** [comment]
There probably ought to be a `From<Vector<A>>` implementation on `HashSet`, but I suppose the idiomatic way to do the conversion is to go via an iterator, like `vector.into_iter().collect::<HashSet<A>>()` (I think, this is from memory and the syntax may be off, but that's the general idea).

**Comment by paytonrules** [comment]
Replace the `A` with a `_` and that works. Thanks!
