### ISSUE TITLE
Error: unexpected `?` when compiling with rustc 0.2.2 

### ISSUE THREAD

**Issue by JivanRoquet** [bodil/im-rs#18]
When compiling `im` 10.2.0 with `cargo build`, the compiler outputs the following error:

```
$> cargo build
Compiling im v10.2.0
error: unexpected `?`
   --> /Users/jivan/.cargo/registry/src/github.com-1ecc6299db9ec823/im-10.2.0/src/nodes/btree.rs:203:19
    |
203 |         BK: Ord + ?Sized,
    |                   ^

error: aborting due to previous error

error: Could not compile `im`.
```

Content of Cargo.toml:
```
(...)

[dependencies]
im = "10.2.0"
```

Using `rustc` version 0.2.2.

Is there any specific compiler flag needed?

**Comment by bodil** [comment]
No compiler flag should be required, but anything much older than the latest stable version of rustc is unsupported. I don't know of any reason it shouldn't work on rustc 1.0 at present, though I can't vouch for it, but 0.2.2 is definitely not going to work. You'll need to upgrade your rustc.

**Comment by JivanRoquet** [comment]
Effectively, I should have checked that first thing. Thanks for the quick reply.
