### ISSUE TITLE
`pool` feature doesn't exist

### ISSUE THREAD

**Issue by Kixiron** [bodil/im-rs#199]
Everything related to pooling is guarded with the `pool` feature, but the `pool` feature isn't declared within the crate's Cargo.toml, meaning it's impossible for users to actually use it

**Comment by bodil** [comment]
As noted in the docs, it only exists on the `im-rc` crate because `refpool` isn't thread safe: https://github.com/bodil/im-rs/blob/master/rc/Cargo.toml#L27
