### ISSUE TITLE
Accessing head and tail requires an Arc clone

### ISSUE THREAD

**Issue by tov** [bodil/im-rs#21]
So, I've been investigating ways to change the API of `ConsList` so that selector methods methods don't have to clone any `Arc`s. You can see the results of my experiment thus far [here](https://github.com/tov/im-rs/tree/ref-access). The main changes are:

  - `ConsList::head` returns `&Arc<A>` instead of `Arc<A>`.
  - `ConsList::tail` return `&ConsList<A>` instead of `ConsList<A>`.
  - `ConsList::uncons` and `ConsList::uncons2` are similarly updated.
  - A method `ConsList::into_cons` that takes the cdr by value rather than reference, to avoid cloning, is added.
  - `into_cons` is used where possible, e.g., in `append`, `reverse`, `from_iter`.

The overall result was a significant speedup to most benchmarks and a tiny slowdown in the append benchmark. The reason for the slowdown, I believe, is that to make this work, I had to revert the representation change that takes the size out of each node. (However, I kept the `Option`-instead-of-bespoke-`enum` aspect of the change.)

In order to see the changes, I added three new benchmarks first:

  - [conslist_sum](https://github.com/tov/im-rs/blob/09384cb058b41794b487deccb794d60d78ef871e/benches/conslist.rs#L47-L50) sums up a `ConsList<u32>` using an iterator.

  - [conslist_sum_no_iter](https://github.com/tov/im-rs/blob/09384cb058b41794b487deccb794d60d78ef871e/benches/conslist.rs#L53-L67) does the same thing, but with manual iteration instead of an iterator.

  - [conslist_reverse](https://github.com/tov/im-rs/blob/09384cb058b41794b487deccb794d60d78ef871e/benches/conslist.rs#L70-L73) reverses a list.

Running these benchmarks on the [unchanged code](https://github.com/tov/im-rs/tree/09384cb), here's the result:

```
test conslist_append      ... bench:  96,154,736 ns/iter (+/- 9,114,543)
test conslist_cons        ... bench:     216,257 ns/iter (+/- 42,042)
test conslist_reverse     ... bench:     218,570 ns/iter (+/- 10,463)
test conslist_sum         ... bench:      94,835 ns/iter (+/- 6,432)
test conslist_sum_no_iter ... bench:      49,140 ns/iter (+/- 3,601)
test conslist_uncons      ... bench:      20,860 ns/iter (+/- 1,138)
```

Here's the final result, after all the changes:

```
test conslist_append      ... bench: 107,298,926 ns/iter (+/- 6,940,051)
test conslist_cons        ... bench:     212,312 ns/iter (+/- 14,665)
test conslist_reverse     ... bench:     153,976 ns/iter (+/- 9,101)
test conslist_sum         ... bench:      49,745 ns/iter (+/- 4,994)
test conslist_sum_no_iter ... bench:       4,535 ns/iter (+/- 722)
test conslist_uncons      ... bench:       2,974 ns/iter (+/- 502)
```

As you can see, most benchmarks have improved, especially `sum_no_iter` (10x) and `uncons` (7x)!

I haven't submitted a pull request, because this is a major API change and I assume you don't want it now/as-is. Note that it would be possible to get the speed benefits in a backward compatible way by adding separate `head_ref`/`tail_ref`/`uncons_ref` methods and leaving the old methods alone. If you want me to work that up, just say so.

Sorry that I'm putting all this effort into what I assume you consider your least interesting data structure. It's the only one I understand yet, but I'm wondering whether similar optimizations could apply to `CatList`.

**Comment by bodil** [comment]
This certainly looks compelling. I'd like to pull this in on a branch for further experimentation, if you don't mind, once I'm done with my current conference flap and can get back to work.

Don't waste your time on `CatList`, btw, if I get RRB vectors working as I expect them to, I'll most likely remove it.

**Comment by tov** [comment]
Yeah, go for it!

I'm looking for things to help with (generally—I’m kinda bored), so if there's anything I can do, let me know.

**Comment by tov** [comment]
I played with this some more, because I wanted to see if we could speed up another data structure in a similar way. So I extended `Vector`, this time in a backward-compatible way, by adding a method `get_ref` and a new iterator type, `RefIter`.

The benchmarks below all create a vector of the given size and then sum its elements. [`vector_sum_get_N`](https://github.com/tov/im-rs/blob/a865b6e06857ae595a69630bdb4b8696e8c5641b/benches/vector.rs#L35-L38) and [`vector_sum_iter_N`](https://github.com/tov/im-rs/blob/a865b6e06857ae595a69630bdb4b8696e8c5641b/benches/vector.rs#L15-L18) use the old API; [`vector_sum_get_ref_N`](https://github.com/tov/im-rs/blob/a865b6e06857ae595a69630bdb4b8696e8c5641b/benches/vector.rs#L81-L90) and
[`vector_sum_iter_ref_N`](https://github.com/tov/im-rs/blob/a865b6e06857ae595a69630bdb4b8696e8c5641b/benches/vector.rs#L35-L38) use the new API. The new API results in a 3–4x speedup for these operations.

```
test vector_sum_get_10          ... bench:         703 ns/iter (+/- 333)
test vector_sum_get_100         ... bench:       6,304 ns/iter (+/- 6,014)
test vector_sum_get_1000        ... bench:      67,581 ns/iter (+/- 98,259)
test vector_sum_get_ref_10      ... bench:         143 ns/iter (+/- 101)
test vector_sum_get_ref_100     ... bench:       1,601 ns/iter (+/- 249)
test vector_sum_get_ref_1000    ... bench:      15,368 ns/iter (+/- 5,585)
test vector_sum_iter_10         ... bench:         644 ns/iter (+/- 193)
test vector_sum_iter_100        ... bench:       4,249 ns/iter (+/- 2,681)
test vector_sum_iter_1000       ... bench:      38,801 ns/iter (+/- 16,136)
test vector_sum_iter_ref_10     ... bench:         207 ns/iter (+/- 129)
test vector_sum_iter_ref_100    ... bench:       1,268 ns/iter (+/- 239)
test vector_sum_iter_ref_1000   ... bench:      11,874 ns/iter (+/- 1,122)
```

**Comment by mitsuhiko** [comment]
I would be very much interested for something like this for hashmaps. I'm using them in [execution-context](https://github.com/mitsuhiko/rust-execution-context) to implement C# style async locals and for a lot of uses there is no need to clone the arc.

**Comment by bodil** [comment]
Everything should now store values directly with no `Arc` (and `ConsList` and `CatList` were removed), so I'll close this.
