### ISSUE TITLE
cargo could use a persistent hash map in it's resolver

### ISSUE THREAD

**Issue by Eh2406** [bodil/im-rs#26]
Hi,

Cargo's resolver has a long standing `TODO`:
"[We should switch to persistent hash maps if we can...](https://github.com/rust-lang/cargo/blob/ea053e357b30fc2464266c309619eb612a6a4cfd/src/cargo/core/resolver/context.rs#L22)"
So when I watched your talk at RustFest Paris I thought I'd make the introductions. So if/when this crate is ready, perhaps a pr thare?

The comment is somewhat out of date. Thanks to a lot of profiling most things are wrapped in `RC`/`ARC` and are bespoke custom persistent data structures. So I suspect it will improve ergonomics more then speed, but I'd be happy to be wrong.

**Comment by bodil** [comment]
Heh, in fact the original `OrdMap` was written exactly because we needed it for a constraint solver. I'm guessing persistent hash maps would be a huge win on very large constraint sets, but mostly equivalent for the more normal sized problems.

For me, it'd be really interesting to see if the API is there yet for real world problems like this - I might actually give it a go before I tag the next major release, there's probably a lot of valuable learning to be had from doing this before I settle on a stable API.

**Comment by Eh2406** [comment]
Using `RC` has improved performance in the past, so persistence matters, but we probably have most of it. We have also done algorithmic improvements, so I don't know of any real world cases where the resolver is the bottleneck. I'd mostly love to be using a library for ergonomics, all the `RC`s/`custom RC wrappers` make the code harder to follow.

>  I might actually give it a go before I tag the next major release

I'd be happy to help anyway I can! For most projects, I'd add a dependency without asking the dependency for permission. But for inclusion in the oficial Rust distribution, I just wanted to make sure you are willing to get the extra attention that may bring.

> there's probably a lot of valuable learning to be had from doing this before I settle on a stable API.

I have asked other [persistence libraries in the past ](https://github.com/orium/rpds/issues/6) and they have found it a useful exercise. They decided that there API was not quite ready. 
Specifically they wanted to add:

- Use `make_mut` to avoid clones when ref count is one. ( I think you already have this.)
- Adding mutable methods to the data structures. ( I think you already have this.)
- Skip boxing keys and values in another `Arc` inside for cheaply cloneable things. ( Similar to your https://github.com/bodil/im-rs/issues/12 I think.)
- Allow the use of `RC` internally instead of `ARC` for single threaded uses.

**Comment by bodil** [comment]
Yes, basically I've got your first two items already in released versions, and the other two are already done in unreleased code. And yes, this is a full time work project for me currently, I can definitely cope with the extra attention. 😊

**Comment by Eh2406** [comment]
Wonderful to hear! So I did a quick audit of `clone`s in the resolver, just to remind myself what is worth changing. The important `clone`s happen [hear](https://github.com/rust-lang/cargo/blob/cedc0ca97e684eb1c19fdb8f1e17da24aba63f9e/src/cargo/core/resolver/mod.rs#L368-L389), when constructing a [BacktrackFrame ](https://github.com/rust-lang/cargo/blob/cedc0ca97e684eb1c19fdb8f1e17da24aba63f9e/src/cargo/core/resolver/mod.rs#L674). The biggest component of which is the [Context](https://github.com/rust-lang/cargo/blob/cedc0ca97e684eb1c19fdb8f1e17da24aba63f9e/src/cargo/core/resolver/context.rs#L16-L39) (although the `BinaryHeap<DepsFrame>` may be worth looking at as well.)
Which brings us back to the original comment, [Activations](https://github.com/rust-lang/cargo/blob/cedc0ca97e684eb1c19fdb8f1e17da24aba63f9e/src/cargo/core/resolver/context.rs#L39) is a huge `HashMap` that is expencive to clone.

I'd start with that `Activations` and see where to go from there.

Another approach is a quick audit of `Rc`s in the resolver. For example [RcList](https://github.com/rust-lang/cargo/blob/cedc0ca97e684eb1c19fdb8f1e17da24aba63f9e/src/cargo/core/resolver/types.rs#L350) can just be replaced with a `ConsList`. And similarly, most use of `RC` could be replaced with less bespoke structures.

**Comment by Eh2406** [comment]
Working from master the [diff is very small ](https://github.com/Eh2406/cargo/commit/60fd86c2167bd8b3189141ca47916a13cfae592e) to get `Activations` moved over. (Congratulations on that!) and it comes with a ~5% improvement.

**Comment by Eh2406** [comment]
I was trying to get a sense of the overhead of using `im` for small cases verses the better asymptotics for big cases. To investigate I made a `criterion` benchmark, of keeping a stack, of all the versions of a HashSet as Items are added one at a time. I think this is the best case for immutable data structures, as using `std and clone` should be `O(stack_size^2)` and `im` should be `O(stack_size)`.

I started with a `usize` as the value. The shape is as predicted, and the crossover is in the low 600s.
![copy](https://user-images.githubusercontent.com/3709504/41861178-8941da5c-786e-11e8-9eb2-54aac9e4069b.png)
Then I realized that is unfair to `im` as `usize` is `copy` so its `clone` is an almost free memcpy. So I tried with `Rc<usize>` with a `clone` of one cache miss. The crossover is in the mid 200s.
![rc](https://user-images.githubusercontent.com/3709504/41861156-7ba54e38-786e-11e8-8b7a-969bc5c689eb.png)

<details>

```rust
#[macro_use]
extern crate criterion;
extern crate im;

use criterion::{Criterion, ParameterizedBenchmark};
use std::rc::Rc;

fn bench(c: &mut Criterion) {
    let parameters = vec![500, 600, 700, 800];
    let benchmark = ParameterizedBenchmark::new("std-HashSet",
                                                |b, &size| {
                                                    b.iter(|| {
                                                        let mut vec = Vec::with_capacity(size);
                                                        let mut seq = std::collections::HashSet::new();
                                                        for i in 0..size {
                                                            seq.insert(i);
                                                            vec.push(seq.clone());
                                                        }
                                                    })
                                                }, parameters)
        .with_function("im-HashSet",
                       |b, &size| {
                           b.iter(|| {
                               let mut vec = Vec::with_capacity(size);
                               let mut seq = im::HashSet::new();
                               for i in 0..size {
                                   seq.insert_mut(i);
                                   vec.push(seq.clone());
                               }
                           })
                       });

    c.bench("clone", benchmark);

    let parameters = vec![200, 300, 400, 500];
    let benchmark = ParameterizedBenchmark::new("std-HashSet",
                                                |b, &size| {
                                                    b.iter(|| {
                                                        let mut vec = Vec::with_capacity(size);
                                                        let mut seq = std::collections::HashSet::new();
                                                        for i in 0..size {
                                                            seq.insert(Rc::new(i));
                                                            vec.push(seq.clone());
                                                        }
                                                    })
                                                }, parameters)
        .with_function("im-HashSet",
                       |b, &size| {
                           b.iter(|| {
                               let mut vec = Vec::with_capacity(size);
                               let mut seq = im::HashSet::new();
                               for i in 0..size {
                                   seq.insert_mut(Rc::new(i));
                                   vec.push(seq.clone());
                               }
                           })
                       });

    c.bench("clone-rc", benchmark);
}

criterion_group!(benches, bench);
criterion_main!(benches);

```

</details>

So given this benchmark I think for cargo:
- `activations` should be faster as an `im` structure. (and that is what we see in experiment.)
- `resolve_features` should be faster with the outer `HashMap` using `im` but with the inner `HashSet` using `Rc` and `std`. Common to have more than 200 crates in the dependency tree, rare to have 600 features in a crate.
- `links` should be faster with `std` as it will be very uncommon to have more the 200 `sys` crates.

**Comment by bodil** [comment]
Update here: I've stabilised the API and am about ready to release - I didn't actually have this thread in mind when working on it, but it looks like I've accidentally managed to address the rough bits you mentioned, probably because I've modelled the final API very closely on std::collections.

I've run the API through a couple of local projects, and it seems sound enough, and looking at the Cargo code I think a port should be very straightforward, so I think I'm going to go ahead and tag the release after agonising about it for just a little while longer.

**Comment by Eh2406** [comment]
Thanks the new api looks good! I really like the `guaranteed drop in for std` style, it makes trying `im` very eazy! :heart: 

One small thing, features are global and additive. So if I rely on `im` types being `Send` or `Sync` then I don't set `no_arc` and all is well. But if later one of my dependencies adds `im` with `no_arc` then I will stop compiling. Or for that matter, any other crate in the same projects dependency tree. 
It would be best if `ARC`/`RC` was a property of each instance of a `im` type, but I think we would need HKT to do that correctly.
Another option is to switch the default. So we would have a `use_arc` feature. If I opt out of it, and I am forced in by another user of `im` then I will be slower than expected but would still compile.

**Comment by Eh2406** [comment]
Cargo is now using `im-rs`. Congratulations, you are part of the rust distribution!
