### ISSUE TITLE
A more flexible way to iterable over an OrdMap

### ISSUE THREAD

**Issue by eventSourcerer** [bodil/im-rs#27]
Hi,

1. Is there a way to iterate backwards on OrdMap efficiently?
2. Is there a way to set a starting point for iteration over OrdMap (perhaps even non-existing key) efficiently?

Great project, BTW!

**Comment by bodil** [comment]
Huh, sorry, I'm sure I replied to this when you posted it, but apparently not...

Anyway, I'm trying to implement this now, and 1. yes, OrdMap's iterators implement `DoubleEndedIterator`, and 2. I'm considering solving this by making a constructor for iterators over a range, something like `map.iter_range(start..end)`, does that sound like a good idea?

**Comment by eventSourcerer** [comment]
A great idea!

**Comment by bodil** [comment]
This proved to be a bit more complicated than I thought, given the current implementation of the iterator. I'm planning to rewrite it soon, but it won't be in time for the upcoming release.

**Comment by bodil** [comment]
Who'd have thought writing an iterator would be this tricky... anyway, it's implemented as `range()` now and should show up in the next release.
