### ISSUE TITLE
Getting an `Iter<T>` instead of `Iter<Arc<T>>` from collections

### ISSUE THREAD

**Issue by Jasper-Bekkers** [bodil/im-rs#28]
Hi,

Right now I'm using a `ConsList` in a single-threaded scenario to implement a builder pattern kind of like this. (I'm aware it might be a bit odd, but it seemed like a natural fit to `cons` into some type of list here).

```
    fn with(self, e: ElementType) -> Self {
        Self {
            elements: im::conslist::cons(e, self.elements),
        }
    }
```

However, later on I need to read the `ConsList` and I wanted to pass around an iterator over it's elements. As it's implemented now (and this could well be a side-effect of how this needs to be implemented - I didn't investigate yet) this turns into an Iterator<Arc<T>> while it would be more natural & closer to `std` collections to have it return an Iterator<T>; it's not a huge deal and transforming between the two is relatively straight forward

```
self.elements.iter().map(|x| (&*x).clone())
```

However, I was wondering if there's a way to do this without having to call `clone`.

- Jasper

**Comment by bodil** [comment]
Well, the `Arc`s are going away in the next major release, but the alternative will be `Iter<&T>`, which isn't quite what you want. I'm thinking it should be possible to have a consuming iterator too, though, but if you're sharing structure the `clone` would just happen behind the scenes instead. In your case, it looks like that wouldn't be a problem.

I'll look into providing consuming iterators for all the data structures it makes sense for (which should be all of them, afaict).

**Comment by Jasper-Bekkers** [comment]
> I'll look into providing consuming iterators for all the data structures it makes sense for (which should be all of them, afaict).

Sweet! It's not a super high priority issue for me since I have a work-around but from an API cleanliness point of view it would make sense to me to have this kind of functionality :-)

**Comment by mitsuhiko** [comment]
@bodil do you mean the arcs go away for iteration or in general? I was wondering if it makes sense to have something like a callback based alternative for `get(&self) -> Option<Arc<T>>` which is like `with<F: FnOnce(Option<&Arc<T>>) -> R, R>(&self, f: F) -> R`.

I don't want to go too off topic here but your comment here made me curious and I could not find anything about the arc changes yet.

**Comment by bodil** [comment]
@mitsuhiko I mean in general - I'm changing values as stored internally from `Arc<A>` to `A: Clone` everywhere, because the performance gain when `A: Copy` is pretty dramatic. So it's left to the user to wrap values that aren't efficiently cloned in `Arc`.
