### ISSUE TITLE
Add an entry api

### ISSUE THREAD

**Issue by Eh2406** [bodil/im-rs#31]
Hi,

So I know that there is a new release in the works, so this may be out of date. But can we add an [Entry API](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#method.entry) like std has? Specifically I have casch of hard to compute values in the form `cache.entry(id).or_insert_with(|| slow_calculation())`, and I don't see a way to do the same in this lib. I'd like to avoid hashing Id more than once if possible, and need to avoid pre computing `slow_calculation` making `insert_*` unhelpful. Or did I miss something that will allow this functionality with the existing methods?

**Comment by bodil** [comment]
I skipped this initially because it doesn't map to purely persistent data structures - now that most of them can act as mutable data structures, I guess it bears revisiting.

**Comment by Eh2406** [comment]
I think do to Lazy evaluation the Haskell `insert_*` would only compute the value if it is needed, but with Rust's Eager evaluation we need more specific `or_insert_with` methods.
