### ISSUE TITLE
RRB Improvements - Direct Append/Direct Tail

### ISSUE THREAD

**Issue by Ygg01** [bodil/im-rs#32]
I see RRB Vectors might appear in near future, and from what I've see they will include transience. I'm wondering about other improvements to RRB Vectors noted in [Improving RRB Vectors with transience](https://hypirion.com/thesis.pdf), namely Direct Append and Direct Tail.

I'd be willing for PR regarding this.

**Comment by bodil** [comment]
The implementation is not nearly done yet, I'd hold off until the branch is ready to merge.

I'm not 100% sure these optimisations are necessary, though (but my reading of the L'Orange paper has been superficial so far), as I've tried to enhance the RRB tree with the head/tail chunking from [the chunked sequences paper](http://deepsea.inria.fr/chunkedseq/esa-2014-long.pdf).

**Comment by Ygg01** [comment]
Interesting read, although I have yet to pierce through all the formulas, but it sounds remarkably similar.

**Comment by Ygg01** [comment]
@bodil Looking at your [chunked-seq branch](https://github.com/bodil/im-rs/tree/chunked-seq), I see it mentions the RRB Vector, but I don't see the radix and relaxed radix nodes/access.

**Comment by bodil** [comment]
@Ygg01 https://github.com/bodil/im-rs/blob/chunked-seq/src/nodes/rrb.rs
