### ISSUE TITLE
Split types into Rc and Arc backed ones

### ISSUE THREAD

**Issue by mitsuhiko** [bodil/im-rs#35]
I was trying to upgrade to latest im but I'm a utility library that needs sync im types, but I do not want to be the fault for forcing sync im on all my users.

Would you be open to a patch to have `Vector<T>` being `Rc` based and `SyncVector<T>` being `Arc` based (and so forth)?

**Comment by bodil** [comment]
It's already on my todo list, so I would be extremely open to a patch or any other way it can be implemented without my having to do the work myself. 😊

My only caveat would be that it would need to have no breaking changes for the base `Vector`, but that seems easily doable.

**Comment by bodil** [comment]
OK, I've been banging my head against this problem for a bit, and came up with a proposed solution which stays inside my hard constraints (doesn't break rls; doesn't need to maintain two copies of the code during normal development), and it is here: 5f6e0e627

It builds two crates, `im-rc` and `im-arc`, identical except for using `Rc` and `Arc` respectively, and pulls them both into a top level `im` crate, which populates the `im` namespace with `im-rc`, as previously without the feature flag, and makes `im-arc` available under the `im::sync` namespace. Consumers can either use `im-rc` or `im-arc` directly, or keep using `im`.

It adds an extra build step when releasing and at initial checkout, but the idea is that the `im-rc` crate is where development happens, and syncing `im-arc` is only necessary when releasing, so all my dev tools still work as previously without any extra work.

Would this work for you?

**Comment by bodil** [comment]
I wasn't quite comfortable with that solution, so I've changed it to keep the original structure of the crate, but with the capability to prepare an additional crate `im-sync` which uses `Arc` instead of `Rc` and is otherwise identical. So, `im` would now be the single threaded version, and `im-sync` the thread safe one, and you'd just pick the crate with the features you need.

**Comment by bodil** [comment]
I flipped the logic, in the end: `im` uses `Arc` and there'll be a new crate `im-rc` which uses `Rc`, as a growing number of optional dependencies require `Arc` and I'd rather have those available on the main crate.

**Comment by mitsuhiko** [comment]
Thanks so much. This is great!

**Comment by orium** [comment]
@bodil Take a look at [https://github.com/orium/archery/](archery).  It's in its very early stages* but it aims to solve this problem.

* Doesn't get expose everything that `Rc/Arc` can do, but will soon.
