### ISSUE TITLE
Clone vs Rc for expensive items

### ISSUE THREAD

**Issue by mitsuhiko** [bodil/im-rs#41]
Trying a bit more with switching older versions of im to the current one I'm trying to figure out if there are some general guidelines about how to deal with items that are more expensive to clone. In particular it's not entirely clear form the API surface currently when a clone actually happens on the item since internally everything is wrapped by a reference counter.

So for instance we have quite a few things that hold Strings and I wonder if it makes sense to wrap this in another layer of refcounting.

**Comment by bodil** [comment]
If you call `clone()` on a data structure, values will be `clone()`d too, but only values that share a leaf node with any modifications you make after cloning. There's no other situation in which values will be cloned (recalling that some methods like `Set::update` perform an implicit clone). Specifically, values are only cloned when we call `Rc::make_mut()` on a leaf node with a reference count > 1.

The intended rule of thumb is that if the data you're storing doesn't implement `Copy`, and you're going to call `clone()` on the collection, you should probably wrap your values in `Rc`s. In the case of small `String`s and `Vec`s, cloning them can be extremely fast, and dereferencing `Rc`s and especially `Arc`s isn't entirely trivial, and as cloning happens lazily, unlike `Vec` etc, it all depends on your use case - you might need to run benchmarks to find out what's more efficient in practice. My guess is that it's probably better to use `String`s directly if you expect them to stay very small, like if you're storing keywords or tokens, at least if you're not cloning them too frequently.

It would probably be good if the docs discussed this... I'll add it to the todo list for the next release.

**Comment by mitsuhiko** [comment]
On second thought that probably does not really make sense.
