### ISSUE TITLE
HashMap<String> remove requires a &String

### ISSUE THREAD

**Issue by mitsuhiko** [bodil/im-rs#43]
This is not a new issue but I did not find one here: a `&str` cannot be passed to `remove` when the hash map key is a `String`. Only `&String` works which is a bit unfortunate.

**Comment by bodil** [comment]
There's a test for this, it should work: https://github.com/bodil/im-rs/blob/master/src/hash/map.rs#L1991

Could you give a code sample that reproduces the problem?

**Comment by mitsuhiko** [comment]
Actually I just tried and it works. I wonder if I accidentally tried against an older version. Closing.
