### ISSUE TITLE
docs.rs failed to build im-12.0.0

### ISSUE THREAD

**Issue by realcr** [bodil/im-rs#45]
Hi, I recently searched for the documentation of `im`. I reached to:
Google took me to this page: https://docs.rs/crate/im/12.0.0
which returns the following error:
```
docs.rs failed to build im-12.0.0
Please check build logs and if you believe this is docs.rs' fault, report into this issue report.
```
I don't know if it's a problem with docs.rs or with this repository.

I also wanted to say that `im-rs` really saved my life, it's one of my favourite crates. Thank you for your work!

**Comment by mitsuhiko** [comment]
It's because `im` depends on too new of a version of rustc which docs.rs does not have yet (https://github.com/onur/docs.rs/issues/233).

I don't think im can do anything about this other than to restore support for older rustc versions.

**Comment by AlexLeung** [comment]
Until that's fixed I guess we can get an idea of the API from the previous version's docs [](https://docs.rs/im/11.0.1/im/)

**Comment by bodil** [comment]
I'm giving up on waiting for it to be fixed on the docs.rs side, I'm going to attempt a workaround.

...which I have to make a new release to even test, so fingers crossed...

**Comment by bodil** [comment]
Seems to have worked!
