### ISSUE TITLE
List::uncons_back missing?

### ISSUE THREAD

**Issue by sdleffler** [bodil/im-rs#5]
`List` says, in its module docs, that it supports append/remove operations on both ends. It certainly supports bidirectional appends/conses, but I went looking for `pop_front` and `pop_back` equivalents; the first is roughly `uncons`, and the second is... nowhere to be found? I didn't see a `head_back`/`tail_back` or `last`/`init` pairing either. Is this intentional?

**Comment by bodil** [comment]
It's an oversight, I'll make a note to add them in for the next release.
