### ISSUE TITLE
String/rope support

### ISSUE THREAD

**Issue by adhoore** [bodil/im-rs#58]
Hi,
I'm using this library for a toy language I'm building.
I want my data structures to be all persistent/immutable.

Right now I'm using Vector and HashMap.
But I also want to do the same for strings.
Are there any plans to add some String implementation?
I see there is a rope branch with an initial implementation.

If you would add a String today would you still use a normal rope?
Doesn't it make more sense to use a RRB vector as underlying type?
I'm really interested in how you would implement it.
I would love to help implement it.

Kind regards,
Alexander

**Comment by bodil** [comment]
I did start an implementation, but I more or less decided at some point that I'd just be reinventing a wheel that's already well implemented elsewhere, [ropey](https://crates.io/crates/ropey) in particular (and I believe Google has a fairly solid implementation for their Xi editor too).

I would highly recommend taking a look at [ropey](https://crates.io/crates/ropey) if you need a rope data structure.
