### ISSUE TITLE
Clone is specified where it not required

### ISSUE THREAD

**Issue by Marwes** [bodil/im-rs#63]
When trying to derive `PartialEq` on a generic type which used an `im-rs` data structure I got an error about a missing `Clone` bound as it appears that `Clone` is specified pervasively on `im-rs`'s impl's.

However, from reading the source and pulling out the minimally necessary methods to remove the bound for `PartialEq for Vector<T>` this should only be necessary on mutating methods, any queries should be able to work without the `Clone` bound.

```rust
// ERROR Clone required
#[derive(PartialEq)]
struct Test<T>(im::Vector<T>);
```

**Comment by bodil** [comment]
Is this worthwhile, though, given that the only value you could produce without `Clone` would be the empty vector? The code used to make this distinction, but I changed it to explicitly require `Clone` everywhere to reduce surprises.

If you have a use case where the distinction would be useful, I'd be happy to reintroduce it.

**Comment by Marwes** [comment]
The example I provided fails to compile due to the `PartialEq` derive thinking it needs `Clone`. It's also an issue in any other generic uses of an `im` type as they need to annotate with `Clone` to work.

It is fixable, sure but I'd argue it is just unnecessary boilerplate. (The specific issue with derives is a bit more annoying as that derive needs special handling of any `T: Clone` bound, which wasn't the case of a hacky derive I have).

**Comment by bodil** [comment]
I've removed constraints on basic constructors and query methods which don't need them, but left them in for methods which don't strictly need them where I feel it would be confusing to take them out, such as some unit constructors. You should be able to derive without adding constraints now.
