### ISSUE TITLE
Compilation Fails

### ISSUE THREAD

**Issue by Kolano** [bodil/im-rs#66]
I'm unable to install cargo-vendor apparently due to problems with im-rd. Something to do with "clippy::should_implement_trait" seemingly referencing: https://github.com/rust-lang/rust/issues/44690

```
cargo install cargo-vendor
...
error[E0658]: scoped lint `clippy::should_implement_trait` is experimental (see issue #44690)
   --> /home/pass/.cargo/registry/src/github.com-1ecc6299db9ec823/im-rc-12.3.0/./src/vector/focus.rs:524:13
    |
524 |     #[allow(clippy::should_implement_trait)] // would if I could
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `im-rc`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-vendor v0.1.23`, intermediate artifacts can be found at `/tmp/cargo-installTbG18U`
```

**Comment by Kolano** [comment]
Sorry, related to im-rc not im-rs

**Comment by bolinfest** [comment]
Has anyone figured out how to workaround this issue? I also tried `cargo install --all-features cargo-vendor`, but I got the same build error (this is even with `cargo 1.34.0-nightly (4e74e2fc0 2019-02-02)` on Linux).

It would be nice if https://github.com/rust-lang/rust/issues/44690 explained how to suppress this error.

**Comment by bolinfest** [comment]
I ended up installing the previous version to workaround the build breakage:

```
cargo install --version 0.1.22 cargo-vendor
```

**Comment by bodil** [comment]
The feature mentioned in the error message should have been stabilised several compiler versions ago, and I've just verified that `cargo install cargo-vendor` works for me on the latest stable and nightly, so I have to ask, are you 100% sure you're running the latest compiler version?

**Comment by Kolano** [comment]
It effects the current package in Ubuntu 18.04.1 and 18.10

**Comment by bodil** [comment]
I've tried running it through various rustc versions, and the earliest version that works is 1.31.0 (where the 2018 edition was stabilised). Ubuntu Cosmic seems to have 1.30.0.

**Comment by bodil** [comment]
Closing this in the absence of any further info.

**Comment by utkonos** [comment]
I'm getting hit by this, and using the older version is a workaround.
