### ISSUE TITLE
Weaken some Fn constraints to FnMut or FnOnce

### ISSUE THREAD

**Issue by lfairy** [bodil/im-rs#7]
Many of the methods that take `Fn`, such as [`HashMap::update`](https://docs.rs/im/10.0.0/im/hashmap/struct.HashMap.html#method.update), only call the given function once or in a single-threaded way. In these cases, the constraints can be weakened to `FnOnce` or `FnMut` respectively.

**Comment by bodil** [comment]
That's probably a good idea, thx for the spot. I've made everything `FnOnce` that can be, but I'm reluctant to change `Fn` to `FnMut` for the remainder because it requires adding a `mut` to the function signature and I'm irrationally worried about the implications.
