### ISSUE TITLE
Why does Debug require Clone ?

### ISSUE THREAD

**Issue by zeroexcuses** [bodil/im-rs#81]
I'm looking at impl of Debug for HashMap.

https://github.com/bodil/im-rs/blob/master/src/hash/map.rs#L1558-L1559

Why do K & V need to have Clone in order to derive Debug for HashMap<K, V> ?

**Comment by bodil** [comment]
I expect it's a leftover from when HashMap itself required Clone on everything. Probably shouldn't be necessary any more.
