### ISSUE TITLE
Set difference is symmetrical difference.

### ISSUE THREAD

**Issue by AljoschaMeyer** [bodil/im-rs#88]
`XyzSet::difference` computes the [symmetrical difference](https://en.wikipedia.org/wiki/Symmetric_difference), not regular [difference](https://en.wikipedia.org/wiki/Complement_(set_theory)#Relative_complement) (aka relative complement). That was fairly surprising to me, it might be a good idea to document this more explicitly than only in the example.

If this was a deliberate choice of terminology, I'd be interested in hearing about the reasoning. Also, would you be open to adding `XyzSet::relative_complement` to the crate?

**Comment by bodil** [comment]
It was deliberate only in the sense that I've recycled the method names from equivalent data structure impls in Haskell, so I couldn't tell you the actual reasoning behind them.

I'd be very happy to take PRs for any additional methods that make sense, and I don't see why this wouldn't. 😊
