### ISSUE TITLE
Find nearby values in OrdSet

### ISSUE THREAD

**Issue by AljoschaMeyer** [bodil/im-rs#95]
Hi, I have a (hopefully small) feature request: Could `OrdSet<T>` expose a method `find_lesser` that takes a `&T` and returns a reference to the greatest value in the set that is less than or equal to `T`, or `None` if no such element exists? Analogously `find_greater` (returns least value that is greater or equal to the argument), and then the same for `OrdMap` (operating on the keys).

From a quick look at the code, it seems like the lookup implementation could support this, but it would take me a while to fully understand what exactly is going on in order to implement this myself.

**Comment by Eh2406** [comment]
this is odd, but works (with std allsow)
```rust
find_lesser = ordset.range(..=t).rev().next();
find_greater = ordset.range(t..).next();
```

**Comment by AljoschaMeyer** [comment]
@Eh2406 thanks =)

I realized I could also use `split_member` for this. So no rush with the request, but it probably still makes sense to explicitly offer that API eventually.

**Comment by bodil** [comment]
It's a good idea, and the range iterator already has code that does exactly this, so it should be trivial to add. I'll put it on the todo list.
