### ISSUE TITLE
How good for ndarray / relational storage/ops?

### ISSUE THREAD

**Issue by mamcx** [bodil/im-rs#96]
I'm building a [relational language](http://tablam.org) where I need to store rows/columns and provide multiple operations of them.

I'm wondering if this crate will be a good fit for this case. The idea is that each value is:

```
cityRows = [<
    id:Int, name:Str;  <-- header
   1 "new york";        <-- row1
   2 "miami";             <-- row2
>]
```

Even scalars like:

```
1 = [1] = [it:Int; 1]
```

From there I need to support the[ relational operators](https://en.wikipedia.org/wiki/Relational_algebra) like filter, joins, groups, selects, etc.

One concern of me is the fact that this mean a lot of cloning and copy of values (I plan to provide a inmutable-first experience) when filtering, making joins, set operators. etc.

P.D: I also experiment with a NDArray-like structure but it make complicated to support mutate the relations. Now I use a Vec<Vec<Value>> to model data by rows. If a NDArray-like design is used on top of im it will be good idea?

**Comment by bodil** [comment]
While you could certainly use the data structures in im to build this, I don't think you'd gain much unless you usually process large amounts of data - eg. the node size of most im data structures is 64, so anything less than that doesn't give you any structural benefits when cloning, and usually std::vec::Vec still provides equivalent or better performance even when cloning heavily until you hit the ~1000-10000 mark, though without the structural sharing benefits, but at those sizes memory is cheap.

I think if you're expecting data structures to almost always contain small amounts of data (hundreds or less), you're better off rolling your own and tuning it appropriately. If you're expecting large data sets (thousands to millions) or a mix, im would be a good choice to build on.

**Comment by mamcx** [comment]
The idea is to build the backend of the language and can't predict how will be used. So I'm looking for a general solution.

**Comment by bodil** [comment]
Well, im tries very hard to be a general solution, so I guess it might work.

I'd consider a different algorithm from `Vector<Vector<A>>`, though, if there is one. `Vector` can be a bit heavy if you're allocating one per row. I don't know much about N-dimensional array algos, but I've got to believe there's a way to do it with some efficiency using a single vector as a backing store.

**Comment by mamcx** [comment]
NDArrays work with a flat Vector and clever indexing to give the illusion of many rows/columns :

`
[1,2,3,a,b,c] = 3 columns * 2 rows in row major
`

The problem with them is what to do if rows/columns are added. It need massive reallocations. I have 
thinking in make pages/sectors where I store at max 1024 rows so at most I reallocate 1024 * columns:

```
Page 1 
   [1,2,3,a,b,c]
Page 2
   [1,2,3,a,b,c]
```

**Comment by bodil** [comment]
Sounds like you want a sparse array, then? HashMap/OrdMap might be a great fit for this, actually. You could use a key datatype that basically contains the coordinate pairs/triples/etc and that will either hash or order, both of which should be trivial to implement.
