### ISSUE TITLE
Zero-sized types

### ISSUE THREAD

**Issue by luteberget** [bodil/im-rs#98]
Hi. I'm experimenting with this cool library, using it for undo/redo in a GUI app, and I stumbled over something, might be a bug. `im::Vector` with a zero-sized type fails to compile, giving a somewhat mysterious error message. Tested on crates.io package v13.0.0 and this im-rs github repository.

I don't have an actual use case for this, but it happened by accident as I was using an empty struct as a placeholder while developing. 

Example:
```rust
fn main() {
    let mut v : im::Vector<()> = im::Vector::new();
    v.push_back(());
}
```

Compiler output:
```
error[E0080]: could not evaluate constant
  --> /home/bjlut/.cargo/registry/src/github.com-1ecc6299db9ec823/sized-chunks-0.3.1/src/inline_array.rs:82:33
   |
82 |     pub const CAPACITY: usize = (Self::HOST_SIZE - Self::HEADER_SIZE) / Self::ELEMENT_SIZE;
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to divide by zero

```

**Comment by bodil** [comment]
Looks like there's no way to test for it and panic early with a more sensible error message until some more `const_fn` features stabilise, so I'll open an issue on [sized-chunks](https://github.com/bodil/sized-chunks) for it to be fixed when these features land in stable.
